config/routes.rb
Pourpedal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "users#new", as: "signup"

  resources :contacts
  resources :users
  resources :sessions
  resources :locations
  resources :charges
  resources :events
  resources :confirmations
  resources :reviews
  resources :photos
  resources :password_resets
  resources :gift_certificates
  resources :trips

  post '/request-reservation' => 'charges#requesting', as: :request_reservation
  post '/reserve' => 'charges#new', as: :new_charge
  post '/codes' => 'confirmations#show'
  post '/redeem_code' => 'charges#redeem'
  post '/confirm_booking' => 'charges#create_with_no_balance_due'
  post '/gift_certificates_charge' => 'charges#gift_certificate_charge', as: :gift_certificate_charge
  # get 'gift_certificates_charge' => 'charges#gift_certificates_charge'
  # post '/gifts' => 'charges#gifts', as: :new_gift

  match 'gift_certificate_confirmation', to: 'gift_certificates#gift_certificate_confirmation', as: :gift_certificate_confirmation
  match '/mobile_gallery', to: 'photos#mobile_gallery', as: :mobile_gallery
  match 'faq', to: 'pages#faqs', as: :faq
  match 'about', to: 'pages#about', as: :about
  match 'upgrade_browser', to: 'pages#upgrade_browser', as: :upgrade_browser
  match '/ui(/:action)', controller: 'ui'
  match '/directions', to: 'pages#directions', as: :directions

  root to: 'pages#index'

end

app/models/gift_certificate.rb
class GiftCertificate < ActiveRecord::Base
  attr_accessible :client_id, :confirmation_id, :client_attributes,
                  :date_purchased, :date_redeemed, :number_purchased,
                  :price_paid, :recipient_first_name, :recipient_email,
                  :recipient_last_name, :special_message

  has_one :client
  has_one :confirmation
  accepts_nested_attributes_for :client, allow_destroy: true

  def client_id
    self.client.try :id
  end

  def client_id=(id)
    self.client = Client.find(id)
  end

end

app/controllers/gift_certificates_controller.rb
class GiftCertificatesController < ApplicationController

  expose(:gift_certificate)
  expose(:client)

  layout 'pages'

  def create
    client = Client.create(params[:client])
    session[:client_id] = client.id
    gift_certificate.client_id = client.id
    if gift_certificate.save
      session[:gift_certificate_id] = gift_certificate.id
      redirect_to gift_certificate_confirmation_path
    else
      render :new
    end
  end

  def gift_certificate_confirmation
    @cert = GiftCertificate.find(session[:gift_certificate_id])
    session[:price] = @cert.number_purchased * 125
  end

end

app/views/gift_certificates/gift_certificate_confirmation.html.haml
- provide(:title, 'confirmation')
%h1.headline
  gift certificate
.headline.paddtop
= form_tag gift_certificate_charge_path do
  %article
    %label.amount
      %h4
        Purchasing #{pluralize(@cert.number_purchased, 'gift certificate')} for #{@cert.recipient_first_name}.
      %br
        %h4
          Amount: #{number_to_currency(session[:price])}
  %p
    %script.stripe-button{"data-amount" => session[:price] * 100, "data-description" => "P&P Gift Certificate", "data-key" => Rails.configuration.stripe[:publishable_key], :src => "https://checkout.stripe.com/v2/checkout.js"}
    = link_to 'cancel', new_gift_certificate_path
%br
%br
%br
%br

app/views/gift_certificates/new.html.haml
- provide(:title, 'gift certificate')
%h1.headline
  The perfect gift for the wine enthusiast!
%h2.headlinetext
  Pour & Pedal gift certificates make it easy to give the gift of wine, bicycling and fun.
%p
  Your lucky recipient will receive an email with a redemption code that can be used to reserve a spot for one of our great #{link_to "pour & pedal events", events_path}.
%p
  Gift certificates cost just $125 per ticket and can be used for any pour & pedal event.
%br
.span4.explainer
  = form_for gift_certificate do |f|
    = fields_for :client do |builder|
      %p.lead About You
      = builder.label :first_name, 'Your First Name'
      = builder.text_field :first_name
      = builder.label :last_name, 'Your Last Name'
      = builder.text_field :last_name
      = builder.label :email, "Your Email"
      = builder.email_field :email
    %p.lead How many tickets would you like to give this recipient?
    = f.select :number_purchased, options_for_select(1..20)
    %p.lead About your Recipient
    = f.label :recipient_first_name, "Recipient's First Name"
    = f.text_field :recipient_first_name
    = f.label :recipient_last_name, "Recipient's Last Name"
    = f.text_field :recipient_last_name
    = f.label :recipient_email, "Recipient's Email"
    = f.email_field :recipient_email
    = f.label :special_message, "Enter a special message for your recipient"
    = f.text_area :special_message, rows: 10
    .clearfix
    = f.submit "Continue", class: 'btn btn-large btn-success pull-right'