config/routes.rb
Pourpedal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "users#new", as: "signup"

  resources :contacts
  resources :users
  resources :sessions
  resources :locations
  resources :charges
  resources :events
  resources :confirmations
  resources :reviews
  resources :photos
  resources :password_resets
  resources :gift_certificates
  resources :trips

  post '/request-reservation' => 'charges#requesting', as: :request_reservation
  post '/reserve' => 'charges#new', as: :new_charge
  post '/codes' => 'confirmations#show'
  post '/redeem_code' => 'charges#redeem'
  post '/confirm_booking' => 'charges#create_with_no_balance_due'
  post '/gift_certificates_charge' => 'charges#gift_certificate_charge', as: :gift_certificate_charge
  # get 'gift_certificates_charge' => 'charges#gift_certificates_charge'
  # post '/gifts' => 'charges#gifts', as: :new_gift

  match 'gift_certificate_confirmation', to: 'gift_certificates#gift_certificate_confirmation', as: :gift_certificate_confirmation
  match '/mobile_gallery', to: 'photos#mobile_gallery', as: :mobile_gallery
  match 'faq', to: 'pages#faqs', as: :faq
  match 'about', to: 'pages#about', as: :about
  match 'upgrade_browser', to: 'pages#upgrade_browser', as: :upgrade_browser
  match '/ui(/:action)', controller: 'ui'
  match '/directions', to: 'pages#directions', as: :directions

  root to: 'pages#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description,
                  :title, :location,
                  :directions, :location_id, :photo_ids, :trips_attributes

  belongs_to :location

  has_and_belongs_to_many :photos
  has_many :trips, dependent: :destroy, inverse_of: :event
  accepts_nested_attributes_for :trips, allow_destroy: true

  has_paper_trail

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  expose(:event)
  expose(:events)
  layout 'pages'
end

app/helpers/events_helper.rb
module EventsHelper

  def location_events(location)
    @events = Event.where(location_id: location.id)
  end
end

app/views/events/index.html.haml
- provide(:title, 'events')
%h1.headline
  our events
%ul
  - events.each do |event|
    .span12.borderline.paddbottom
      .span3.eventlisting
        %h3.headlinetext
          = link_to event.title, event
        %img
          - event.photos.each do |photo|
            - if photo.primary_for_event?
              = link_to (image_tag photo.photo.medium, class: 'img-polaroid'), event_path(event)
      .span8
        .eventdescription
          %li
            = truncate event.description, length: 500
            = link_to 'read more', event
    .clearfix

app/views/events/show.html.haml
- provide(:title, event.title)
%h1.headline
  = event.title
%p.pull-right.goback
  = link_to "back to event listings", events_path
%img
  - event.photos.each do |photo|
    - if photo.primary_for_event?
      = image_tag photo.photo.headline, class: 'img-polaroid'
%p.description
  = event.description
.maxheight
  %table.table
    %thead
      %tr
        %th.span3 Date
        %th.span3 Price
        %th.span3 Spots Available
        %th.span3
    %tbody
      %td
        - event.trips.sort_by!{|e| e[:date]}
        - event.trips.each do |e|
          - if e.date > Date.today + 1
            %tr
              %td
                = e.title
              %td
                = number_to_currency(e.price)
              - if e.spots_available > 0
                %td
                  #{pluralize(e.spots_available, 'spots')} available
                %td
                  = form_tag '/request-reservation' do
                    = hidden_field_tag :trip_id, e.id
                    = submit_tag "Reserve Now", class: 'btn btn-success'
              - else
                %td
                  SOLD OUT
                %td