config/routes.rb
Pourpedal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "users#new", as: "signup"

  resources :contacts
  resources :users
  resources :sessions
  resources :locations
  resources :charges
  resources :events
  resources :confirmations
  resources :reviews
  resources :photos
  resources :password_resets
  resources :gift_certificates
  resources :trips

  post '/request-reservation' => 'charges#requesting', as: :request_reservation
  post '/reserve' => 'charges#new', as: :new_charge
  post '/codes' => 'confirmations#show'
  post '/redeem_code' => 'charges#redeem'
  post '/confirm_booking' => 'charges#create_with_no_balance_due'
  post '/gift_certificates_charge' => 'charges#gift_certificate_charge', as: :gift_certificate_charge
  # get 'gift_certificates_charge' => 'charges#gift_certificates_charge'
  # post '/gifts' => 'charges#gifts', as: :new_gift

  match 'gift_certificate_confirmation', to: 'gift_certificates#gift_certificate_confirmation', as: :gift_certificate_confirmation
  match '/mobile_gallery', to: 'photos#mobile_gallery', as: :mobile_gallery
  match 'faq', to: 'pages#faqs', as: :faq
  match 'about', to: 'pages#about', as: :about
  match 'upgrade_browser', to: 'pages#upgrade_browser', as: :upgrade_browser
  match '/ui(/:action)', controller: 'ui'
  match '/directions', to: 'pages#directions', as: :directions

  root to: 'pages#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  expose(:review)
  expose(:reviews) { Review.order("featured").page(params[:page]).per(5)}

  layout 'pages'

  def show
  end

  def create
    if review.save
      redirect_to reviews_path, notice: "Your review has been submitted!"
      NotificationMailer.new_review(review).deliver
    else
      render :new
    end
  end

end

app/views/reviews/index.html.haml
- provide(:title, 'reviews')
%h1.headline
  reviews
.paddtop
.span8
  %p.headlinetext
    Pour & Pedal bike tours are awesome! But don't take our word for it; here's what our clients have to say..
  %p.pull-right
    = link_to "submit your review", new_review_path, class: 'btn btn-success'
  .paddtop
  .span6
    - reviews.each do |review|
      - if review.featured?
        %p.winecolor.paddtop
          = review.content
      - else
        %p
        = review.content
      %h3.pull-right
        - if review.hometown.blank?
          #{review.name}
        - else
          #{review.name}, #{review.hometown}
      .paddtop
      .clearfix.borderline
    .center
      = paginate reviews
.span3
  = render 'shared/trip_advisor'

app/views/reviews/new.html.haml
- provide(:title, 'submit a review')
%h1.headline
  Submit your review of pour & pedal

= form_for review do |f|
  - if review.errors.any?
    .error_messages
      %h2 Oops! You spilled wine on the form..
      %ul
        - for message in review.errors.full_messages
          %li= message
  = f.label :name
  = f.text_field :name
  = f.label :email, "Email (won't be published)"
  = f.email_field :email
  = f.label :hometown, "City, State, Country"
  = f.text_field :hometown
  = f.label :content, "Your review"
  = f.text_area :content, rows: 15, class: 'input-xxlarge'
  .clearfix
  = f.submit "Submit your review", class: 'btn btn-large btn-success'
  = link_to "Cancel", reviews_path

app/views/reviews/show.html.haml
- provide(:title, 'review')
%h1.paddtop
  .explainer
    %p.lead
      = review.content
    %h3
      - if review.hometown.blank?
        #{review.name}
      - else
        #{review.name}, #{review.hometown}