config/routes.rb
Pourpedal::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "logout" => "sessions#destroy", as: "logout"
  get "login" => "sessions#new", as: "login"
  get "signup" => "users#new", as: "signup"

  resources :contacts
  resources :users
  resources :sessions
  resources :locations
  resources :charges
  resources :events
  resources :confirmations
  resources :reviews
  resources :photos
  resources :password_resets
  resources :gift_certificates
  resources :trips

  post '/request-reservation' => 'charges#requesting', as: :request_reservation
  post '/reserve' => 'charges#new', as: :new_charge
  post '/codes' => 'confirmations#show'
  post '/redeem_code' => 'charges#redeem'
  post '/confirm_booking' => 'charges#create_with_no_balance_due'
  post '/gift_certificates_charge' => 'charges#gift_certificate_charge', as: :gift_certificate_charge
  # get 'gift_certificates_charge' => 'charges#gift_certificates_charge'
  # post '/gifts' => 'charges#gifts', as: :new_gift

  match 'gift_certificate_confirmation', to: 'gift_certificates#gift_certificate_confirmation', as: :gift_certificate_confirmation
  match '/mobile_gallery', to: 'photos#mobile_gallery', as: :mobile_gallery
  match 'faq', to: 'pages#faqs', as: :faq
  match 'about', to: 'pages#about', as: :about
  match 'upgrade_browser', to: 'pages#upgrade_browser', as: :upgrade_browser
  match '/ui(/:action)', controller: 'ui'
  match '/directions', to: 'pages#directions', as: :directions

  root to: 'pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/alert.rb
class Alert < ActiveRecord::Base
  attr_accessible :content, :headline, :show_alert
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :phone, :zipcode,
  :trip_id, :date_paid, :amount_paid

  has_one :trip, through: :confirmation
  has_one :confirmation
  belongs_to :gift_certificate

  has_paper_trail

end

app/models/confirmation.rb
class Confirmation < ActiveRecord::Base
  attr_accessible :client_id, :confirmation_number, :created_by,
  :expiration_date, :is_expired, :is_used, :source, :value, :trip_id,
  :is_cancelled, :gift_certificate_id, :number_of_tickets

  belongs_to :trip
  belongs_to :client
  belongs_to :gift_certificate

  validates_presence_of :confirmation_number

  has_paper_trail

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :message, :phone, :responded,
  :response_date, :responded_by, :notes

  has_paper_trail
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :date, :description,
                  :title, :location,
                  :directions, :location_id, :photo_ids, :trips_attributes

  belongs_to :location

  has_and_belongs_to_many :photos
  has_many :trips, dependent: :destroy, inverse_of: :event
  accepts_nested_attributes_for :trips, allow_destroy: true

  has_paper_trail

end

app/models/faq.rb
class Faq < ActiveRecord::Base
  attr_accessible :answer, :question

  has_paper_trail
end

app/models/gallery_image.rb
class GalleryImage < ActiveRecord::Base
  attr_accessible :caption, :photo, :title, :photo_cache,
                  :remove_photo
  mount_uploader :photo, PhotoUploader

  validates_presence_of :title, :photo, :caption

  has_paper_trail

end

app/models/gift_certificate.rb
class GiftCertificate < ActiveRecord::Base
  attr_accessible :client_id, :confirmation_id, :client_attributes,
                  :date_purchased, :date_redeemed, :number_purchased,
                  :price_paid, :recipient_first_name, :recipient_email,
                  :recipient_last_name, :special_message

  has_one :client
  has_one :confirmation
  accepts_nested_attributes_for :client, allow_destroy: true

  def client_id
    self.client.try :id
  end

  def client_id=(id)
    self.client = Client.find(id)
  end

end

app/models/home_image.rb
class HomeImage < ActiveRecord::Base
  attr_accessible :photo, :position, :title, :photo_cache,
                  :remove_photo

  mount_uploader :photo, PhotoUploader

  validates_presence_of :title, :photo
  validates_uniqueness_of :position

  has_paper_trail
end

app/models/home_text.rb
class HomeText < ActiveRecord::Base
  attr_accessible :content, :visible
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :name, :photos_attributes, :description, :events_ids
  has_many :photos, dependent: :destroy, inverse_of: :location
  accepts_nested_attributes_for :photos, allow_destroy: true

  has_many :events

  has_paper_trail
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :location_id, :photo, :photo_cache,
                  :remove_photo, :title, :event_ids, :primary_for_location,
                  :primary_for_event
  belongs_to :location, inverse_of: :photos
  has_and_belongs_to_many :events
  mount_uploader :photo, PhotoUploader

  validates_presence_of :title, :photo

  has_paper_trail

  before_save :set_primary

  def set_primary
    if self.primary_for_location?
      current_primary = self
      if self.location_id
        location_id = self.location_id
        photos = Photo.where(location_id: location_id, primary_for_location: true)
      else
      end
        photos.each do |photo|
          if photo == current_primary
          else
            photo.primary_for_location = false
            photo.save
          end
        end
    elsif self.primary_for_event?
      current_primary = self
      if self.events[0].id
        event_id = self.events[0].id
        photos = Photo.where(event_id: event_id, primary_for_event: true)
      else
      end
        photos.each do |photo|
          if photo == current_primary
          else
            photo.primary_for_event = false
            photo.save
          end
        end
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :content, :email, :hometown, :name, :featured

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :hometown, presence: true, length: { maximum: 50 }
  validates :content, presence: true

  has_paper_trail

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  attr_accessible :date, :event_id, :price, :spots_available, :tickets_sold, :title

  has_many :confirmations
  has_many :clients, through: :confirmations
  belongs_to :event, inverse_of: :trips

  validates_presence_of :title, :date, :price

  has_paper_trail

  after_save :set_summary_url

  def set_summary_url
    if self.summary.nil?
      self.summary = "http://pourandpedal.com/trips/#{self.id}"
      self.save
    else
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :email, :password, :password_confirmation, :name

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :name
  validates_uniqueness_of :name

  has_paper_trail

  before_save :set_username

  def set_username
    self.username = self.email
  end
end

app/controllers/ui_controller.rb
class UiController < Hashrocket::UiController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = 'pour & pedal'
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper

  def location_events(location)
    @events = Event.where(location_id: location.id)
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/_alert_banner.html.haml
.clearfix
- @alerts = Alert.all
- @alerts.each do |alert|
  - if alert.show_alert?
    .explainerred
      %h3.middling
        = alert.headline
      %p.bodyjustify
        = alert.content
      %p.right
        last updated #{time_ago_in_words(alert.updated_at)} ago
.clearfix

app/views/layouts/_footer.html.haml
%footer
  / .padright
  /   .fb-like.pull-right.padfb{"data-font" => "lucida grande", "data-href" => "http://pourandpedal.com", "data-layout" => "button_count", "data-send" => "true", "data-show-faces" => "true", "data-width" => "450"}

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to image_tag('pourpedal_header_logo_small.png'), root_path, id: "logo"
      %nav

        %ul.nav
          %li{:class => "#{'active' if current_page?(about_path)}"}=link_to "about", about_path
          %li{:class => "#{'active' if current_page?(faq_path)}"}=link_to "faqs", faq_path
          %li{:class => "#{'active' if current_page?(photos_path)}"}=link_to "gallery", photos_path
          %li{:class => "#{'active' if current_page?(reviews_path)}"}=link_to "reviews", reviews_path
          %li{:class => "#{'active' if current_page?(events_path)}"}=link_to "events", events_path
          %li{:class => "#{'active' if current_page?(locations_path)}"}=link_to "directions", directions_path
          %li{:class => "#{'active' if current_page?(new_contact_path)}"}=link_to "contact", new_contact_path
          %li
            %a{"data-toggle" => "modal", :href => "#myreservation", :role => "button"} my reservation
        .btn.winebutton
          = link_to "gifts", new_gift_certificate_path
        - if logged_in?
          %li
            = link_to "Sign out", logout_path
  .clearfix
#myreservation.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel Enter your confirmation number
  .modal-body
    %p
      = form_tag '/codes' do
        = text_field_tag :code
        %br
        = submit_tag "Submit", class: 'btn btn-danger'
        %br
          = image_tag('wine-bike-small.png', class: 'pull-right')

app/views/layouts/_typekit.html.erb
<meta name="google-site-verification" content="BddC_Fp94UJQWDwTagQFrZ6ind1XbxQy063AONV3V-g" />
<link href='http://fonts.googleapis.com/css?family=Rokkitt:400,700' rel='stylesheet' type='text/css'>
<meta http-equiv="X-UA-Compatible" content="chrome=1">
<!--[if IE]>
    <script type="text/javascript"
     src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js"></script>

    <style>
     .chromeFrameInstallDefaultStyle {
       width: 100%; /* default is 800px */
       border: 5px solid blue;
     }
    </style>

    <div id="prompt">
     <!-- if IE without GCF, prompt goes here -->
    </div>

    <script>
     // The conditional ensures that this code will only execute in IE,
     // Therefore we can use the IE-specific attachEvent without worry
     window.attachEvent("onload", function() {
       CFInstall.check({
         mode: "inline", // the default
         node: "prompt"
       });
     });
    </script>
  <![endif]-->

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/typekit'
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application', 'sparkle', 'home'
    = csrf_meta_tags
    = yield :head
    /[if IE]
      = javascript_include_tag 'html5'
  %body
    #fb-root
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    #wrap
      = render 'layouts/header'
      = render 'layouts/alert_banner'
      #main
        .container
          = render 'flashes'
          = yield
      #push
      #footer
        = render 'layouts/footer'

app/views/layouts/charges.html.haml
!!!
%html
  %head
  %body
    = yield

app/views/layouts/gallery.html.haml
!!!
%html
  %head
    %meta{:content => "text/html;charset=iso-8859-1", "http-equiv" => "Content-Type"}
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport"}/
    %script{:src => "http://www.google.com/jsapi", :type => "text/javascript"}
    %link{:href => "http://fonts.googleapis.com/css?family=Gochi+Hand", :rel => "stylesheet", :type => "text/css"}/
    = render 'layouts/typekit'
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag    'application', 'gallery'
    = stylesheet_link_tag 'application', 'mobile' if mobile_device?
    = javascript_include_tag 'application', 'gallery'
    = csrf_meta_tags
    = yield :head
    /[if IE]
      = javascript_include_tag 'html5'
  %body
    #wrap
      = render 'layouts/header'
      #main
        .container
          = render 'flashes'
          = yield

app/views/layouts/ie.html.erb
  <!--[if lt IE 8]>
  <meta http-equiv="REFRESH" content="0;url=http://pour-and-pedal.herokuapp.com/upgrade_browser">
<![endif]-->

app/views/layouts/pages.html.haml
!!!
%html
  %head
    = render 'layouts/typekit'
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag 'application', 'pages'
    = javascript_include_tag 'application', 'sparkle', 'home'
    = csrf_meta_tags
    = yield :head
    /[if IE]
      = javascript_include_tag 'html5'
  %body
    #fb-root
    :javascript
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    #wrap
      = render 'layouts/header'
      #main
        .container
          = render 'flashes'
          = yield
      #push
      #footer
        = render 'layouts/footer'

app/views/shared/_code_summary.html.haml
%h1.headline
  Redemption Code Summary
.explainer
  %p
    Here are the details for your redemption code:

  = confirmation.confirmation_number
  = number_to_currency(confirmation.value)
  %p
    Expires on
    = confirmation.expiration_date
  %h2
    What good is this code if you don't use it?
  %br
    = link_to "Let's find a trip!", events_path, class: "btn btn-large btn-success"

app/views/shared/_reservation.html.haml
%h1.headline
  Reservation Summary
.explainer
  %p
    Confirmation Number: #{confirmation.confirmation_number}
  %p
    Email: #{confirmation.client.email}

  %ul
    %li
      #{confirmation.client.first_name} #{confirmation.client.last_name}
    %li
      = confirmation.trip.event.title
    %li
      = confirmation.trip.date.to_formatted_s(:long_ordinal)
    %li
      #{pluralize(confirmation.client.tickets_purchased, 'ticket')}
    %li
      Total amount paid #{number_to_currency(confirmation.client.amount_paid)}
    %li
      Directions:
      = confirmation.trip.event.directions

app/views/shared/_trip_advisor.html.erb
<div id="TA_selfserveprop818" class="TA_selfserveprop">
<ul id="05SmOQDsw" class="TA_links 6fx9ho93R">
<li id="OzUP3NsCD" class="WnOUm620M">14 reviews of <a target="_blank" href="http://www.tripadvisor.com/Attraction_Review-g48134-d2202658-Reviews-North_Fork_Bicycle_Tours-Mattituck_North_Fork_Long_Island_New_York.html">North Fork Bicycle Tours</a> in Mattituck</li>
</ul>
</div>
<script src="http://www.jscache.com/wejs?wtype=selfserveprop&amp;uniq=818&amp;locationId=2202658&amp;lang=en_US&amp;rating=true&amp;nreviews=5&amp;writereviewlink=true&amp;popIdx=true&amp;iswide=false&amp;border=true"></script>